version: '3'

services:

    postgres:
        container_name: postgres
        image: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: yakasserole
            POSTGRES_PASSWORD: F8Pf7tM
            POSTGRES_DB: app
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d
            - ./data/postgres:/var/lib/postgresql/data

    pgadmin:
        container_name: pgadmin
        image: chorss/docker-pgadmin4
        ports:
            - '5050:5050'
        volumes:
            - ./data/pgadmin:/data
        links:
            - postgres:postgres
